# -*- coding: utf-8 -*-
"""DataCluster_WIL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtjyH7dCe-1cMHjHEn8Z3cJgwWeRd6a3

# **Customer Segmentation Using K-Means Clustering**

This analysis focuses on segmenting telecommunications customers into meaningful groups using K-Means clustering. The objective is to identify distinct customer segments based on demographic and service-related attributes to support churn analysis and retention strategy development.
"""

# Import required libraries for data handling, clustering, and visualization
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

"""## **Dataset Loading and Validation**

The preprocessed customer dataset provided by the Data Engineering team was loaded into the analysis environment. The dataset was previously cleaned, encoded, and scaled to ensure suitability for clustering analysis.

Dataset dimensions were verified to confirm successful loading and data integrity before proceeding with segmentation.
"""

# Load the preprocessed customer dataset provided by the Data Engineer
data = pd.read_csv("churn_clustering_ready.csv")


# Display first few rows to verify successful loading
data.head()

# Check the number of rows and columns in the dataset
# This helps verify that the dataset was loaded correctly
data.shape

"""## **Feature Preparation for Clustering Analysis**

Since K-Means is an unsupervised learning algorithm, the target variable Churn was excluded from the clustering process. This ensures that customer segments are formed purely based on behavioural and demographic similarities rather than predefined outcomes.

The remaining features were used to identify natural groupings within the customer base.
"""

# Remove 'Churn' column before clustering
# K-Means is an unsupervised algorithm and should not use target labels
X = data.drop('Churn', axis=1)

X.head()

"""## **Determining the Optimal Number of Customer Segments**
The Elbow Method was applied to determine the optimal number of clusters. This technique evaluates the within-cluster variance (inertia) for different values of K.

A noticeable bend in the inertia curve was observed at K = 4, indicating diminishing improvements beyond this point. Therefore, four clusters were selected as the optimal number of customer segments.
"""

# Apply Elbow Method to determine optimal number of clusters
# Inertia measures within-cluster variance

inertia = []

K_range = range(1,11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

# ELBOW CURVE
# # Plot inertia values to visually identify optimal cluster number
plt.figure(figsize=(8,5))

plt.plot(K_range, inertia, marker='o')

plt.title("Elbow Method for Optimal Number of Clusters")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")

plt.show()

"""## **Customer Segmentation Using K-Means**

A K-Means clustering model was trained using the optimal number of clusters identified through the Elbow Method. Each customer was assigned to a cluster representing similar characteristics and service usage patterns.

The resulting cluster labels were appended to the dataset for further analysis and interpretation.
"""

from sklearn.cluster import KMeans
# Train K-Means model using optimal number of clusters (K = 4)
kmeans = KMeans(n_clusters=4, random_state=42)

# Assign cluster labels to each customer
data['Cluster'] = kmeans.fit_predict(X)

"""## **Verification of Cluster Assignment**

The clustering results were validated by checking the unique cluster labels generated by the K-Means algorithm. The output confirms that customers were successfully segmented into four distinct clusters.

A preview of the dataset was displayed to ensure that cluster assignments were correctly added.
"""

# Verification of Cluster Assignment
sorted(data['Cluster'].unique())
data.head()

"""## **Visualisation of Customer Segments**

Principal Component Analysis (PCA) was applied to reduce the dataset dimensions to two components for visualization purposes. This enables graphical representation of customer segments while preserving underlying data variance.

The scatter plot illustrates the separation between customer groups formed through clustering.
"""

# Reduce dataset dimensions to 2 components for visualization purposes
pca = PCA(n_components=2)
pca_components = pca.fit_transform(X)

# Visualize customer segments formed by K-Means clustering
plt.scatter(
    pca_components[:,0],
    pca_components[:,1],
    c=data['Cluster'],
    cmap='viridis'
)

plt.title("Customer Segmentation using K-Means")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.colorbar(label="Cluster")
plt.show()

"""## **Linking Customer Segmentation to Churn Behaviour**

Although clustering was performed without using churn labels, churn rates were analysed across clusters after segmentation. This allows identification of customer groups with higher churn risk and supports targeted retention initiatives.
"""

# Cluster Interpretation
data.groupby('Cluster')['Churn'].mean()

"""## **Cluster Profiling and Analysis**

To interpret customer segments, average feature values within each cluster were analysed. This profiling helps identify behavioural patterns, service preferences, and potential churn tendencies associated with each customer group.

The insights derived from this analysis support data-driven decision-making for customer retention strategies.
"""

# Analyse average feature values within each cluster
cluster_summary = data.groupby('Cluster').mean()
cluster_summary

data.to_csv("clustered_customers_k4.csv", index=False)

"""## **Final Cluster Insights and Business Interpretation**

The K-Means clustering analysis successfully segmented customers into four distinct groups based on demographic characteristics, service usage patterns, and subscription behaviour. The Elbow Method identified four clusters as the optimal segmentation structure, enabling meaningful differentiation among customer groups.

Analysis of churn behaviour across clusters revealed significant variation in customer retention patterns. Clusters 0 and 1 demonstrated relatively low churn rates (approximately 11–14%), indicating stable and loyal customer segments. These customers generally exhibit longer tenure or lower service costs, suggesting higher satisfaction and reduced likelihood of service discontinuation.

In contrast, Clusters 2 and 3 showed substantially higher churn rates exceeding 40%, identifying these groups as high-risk customer segments. These customers are characterised by shorter tenure and a higher concentration of month-to-month contracts, indicating weaker long-term commitment to the service provider. Additionally, differences in internet service type further distinguish these segments, highlighting potential service experience or pricing sensitivities.

Overall, the clustering results provide valuable insights into customer behaviour without directly utilising churn labels during segmentation. By linking clusters with churn outcomes after analysis, the organisation can prioritise retention strategies toward newly acquired and flexible-contract customers who demonstrate the greatest risk of attrition.
"""